model:
  model_path: Qwen3-8B-Base
  attn_implementation: flash_attention_2

data:
  train_path: tulu-3-sft-mixture
  data_type: conversation
  chat_template: chatml
  max_seq_len: 2048
  train_size: 750000
  text_keys: messages

train:
  output_dir: Qwen3-8B-Base-sft-tulu
  data_parallel_mode: fsdp1
  ulysses_parallel_size: 1
  global_batch_size: 8
  micro_batch_size: 1
  rmpad: false
  rmpad_with_pos_ids: true
  bsz_warmup_ratio: 0.007
  dyn_bsz_margin: 0
  dyn_bsz_buffer_size: 200
  optimizer: adamw
  lr: 1.0e-4
  lr_decay_style: cosine
  num_train_epochs: 3
  max_grad_norm: 1.0
  enable_mixed_precision: true
  enable_gradient_checkpointing: true
  enable_full_shard: true
  enable_fsdp_offload: false
  enable_activation_offload: false
  init_device: meta
  enable_full_determinism: false
  empty_cache_steps: 500
  ckpt_manager: dcp
  load_checkpoint_path: ""
  save_steps: 100
  save_epochs: 1
  save_hf_weights: false
  wandb_project: VeOmni
  wandb_name: Qwen3-8B-Base-sft-tulu
