
# # Tests layout

name: GPU e2e tests

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
      - v0.*
    paths:
      - "**/*.py"
      - .github/workflows/gpu_e2e_test.yml
  pull_request:
    branches:
      - main
    paths:
      - "**/*.py"
      - .github/workflows/gpu_e2e_test.yml

# Cancel jobs on the same ref if a new one is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

# Declare permissions just read content.
permissions:
  contents: read

env:
  IMAGE: "verl-ci-cn-beijing.cr.volces.com/veomni/open_veomni-gpu:pytorch_25_03_py3_cuda12_8"
  DYNAMIC_RUNNER_ENDPOINT: "https://sd4hav466omp034ocfn0g.apigateway-cn-beijing.volceapi.com/veomni/runner"
  NCCL_DEBUG: "WARN"

jobs:
  setup:
    if: github.repository_owner == 'ByteDance-Seed'
    runs-on: ubuntu-latest
    outputs:
      runner-label: ${{ steps.create-runner.outputs.runner-label }}
      mlp-task-id: ${{ steps.create-runner.outputs.mlp-task-id }}
    steps:
      - uses: actions/checkout@v4
      - id: create-runner
        uses: volcengine/vemlp-github-runner@v1
        with:
          mode: "create"
          faas-url: "${{ env.DYNAMIC_RUNNER_ENDPOINT }}"
          mlp-image: "${{ env.IMAGE }}"

  gpu_unit_tests:
    if: github.repository_owner == 'ByteDance-Seed'
    needs: setup
    runs-on: [ "${{ needs.setup.outputs.runner-label || 'L20x8' }}" ]
    timeout-minutes: 60 # Increase this timeout value as needed
    env:
      HF_HUB_ENABLE_HF_TRANSFER: 1
      NCCL_DEBUG: "WARN"
      CI_MODEL_DIR: "/root/models/Qwen"
      CI_DATASET_DIR: "/root/models/hf_data"

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
            fetch-depth: 0
      - name: Sync dependencies
        run: |
          uv sync --frozen --extra gpu --group dev
      - name: Run e2e training test
        run: |
          uv run pytest -s -x tests/e2e/test_e2e_training.py


  cleanup:
    runs-on: ubuntu-latest
    needs:
      [
        setup,
        gpu_unit_tests,
      ]
    if: always()
    steps:
      - id: destroy-runner
        uses: volcengine/vemlp-github-runner@v1
        with:
          mode: "destroy"
          faas-url: "${{ env.DYNAMIC_RUNNER_ENDPOINT }}"
          mlp-task-id: "${{ needs.setup.outputs.mlp-task-id }}"
